apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: beneficiary-service
  description: Manages beneficiary details and validation (.NET 8)
spec:
  type: openapi
  lifecycle: production
  owner: group:default/backend-team
  providesApis:
    - api:default/mobile-gateway
    - api:default/transfer-engine
  dependsOn:
    - component:default/t24-core-banking
  definition: |
    openapi: 3.0.0
    info:
      title: beneficiary Engine API
      version: 1.0.0
    paths: {}
